[package]
name = "clipboard_sync"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "*"
serde = { version = "1.0.130", features = ["derive"] }
bincode = "1.3.3"